"""empty message

Revision ID: 9114ee66e630
Revises: 
Create Date: 2018-12-03 13:44:06.264815

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9114ee66e630'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('synonym',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('synonym', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('synonym')
    )
    op.create_table('snapshot',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('spans_from', sa.DateTime(), nullable=False),
    sa.Column('spans_to', sa.DateTime(), nullable=False),
    sa.Column('statistics', sa.JSON(), nullable=False),
    sa.Column('sentiment', sa.Float(), nullable=False),
    sa.Column('synonym_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['synonym_id'], ['synonym.id'], ),
    sa.PrimaryKeyConstraint('id', 'synonym_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('snapshot')
    op.drop_table('synonym')
    # ### end Alembic commands ###
