"""add snapshot

Revision ID: c144238e7ff4
Revises: 
Create Date: 2018-11-30 11:36:40.231788

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c144238e7ff4'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('snapshot',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('spans_from', sa.DateTime(), nullable=False),
    sa.Column('spans_to', sa.DateTime(), nullable=False),
    sa.Column('keywords', sa.JSON(), nullable=False),
    sa.Column('sentiment', sa.Float(), nullable=False),
    sa.Column('synonym', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('snapshot')
    # ### end Alembic commands ###
