"""made synonym id unique

Revision ID: dd2934254218
Revises: 9114ee66e630
Create Date: 2018-12-12 14:51:30.933087

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dd2934254218'
down_revision = '9114ee66e630'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('snapshot', 'synonym_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.create_unique_constraint(None, 'snapshot', ['synonym_id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'snapshot', type_='unique')
    op.alter_column('snapshot', 'synonym_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
